### ISSUE TITLE
Bug - low priority - Analysis - Advanced filter with wild card and numbers

### ISSUE THREAD

**Issue by martingpritchard** [smap-consulting/smapserver#433] opened 2019-03-06 07:09 UTC
### Version
19.02
sg. smap.com.au

### Expected Behaviour
When performing an advanced filter in the Analysis tables using the like and wildcard, SMAP should consistently return accurate search results that match the search parameters. 

### Actual Behaviour
Pending the search parameters, I'm seeing mixed results when ${fieldname} like '%nn%' is used. where nn is a number. 

### Steps to reproduce the problem
e.g. sg.smap.com.au
project: Tonga Skills
Go to Analysis
Open table for Application Form
Click gear icon.
I enter ${_hrk} like '%84%' in the Advanced Filter box. 
Click Save button.
Shows no results

I click the settings (gear) icon again
I enter ${_hrk} like '%_84%' in the Advanced Filter box. 
Click Save button.
Many matching results are saved

If I try the same on the email field (standard text field)
${email} like '%18%'
Produces no results even though there are two or more entries with 18 in them.

${email} like '%1%'
Produces lots of results, with several showing xxx18xxx@xxxx.xxxx and also several with xxxa1xxxx@xxx.xxx

${email} like '%a1%'
Produces no results even though there are two or more entries with a1 in them.

If I try the same on the email field
${email} like '%18@%'
Produces no results even though there are two or more entries with 18@ in them.

There are a lot of other variables to test. I've only tested with like '%%'

### Server
sg.smap.com.au

### Organisation
PREA?

### Project
Tonga Skills 

### Form Name
Application Form
(also completion report, I think same for all forms)

**Comment by nap2000** [comment] 2019-05-20 00:37
The problem was caused by the advanced filter definition not being encoded before being added to the URL.  This should be fixed in the next release.

**Comment by atl2017** [comment] 2019-06-07 18:47
I did few test and works fine:

![image](https://user-images.githubusercontent.com/29519901/59126461-c5b33a80-892a-11e9-9065-a792696fdc55.png)

**Comment by atl2017** [comment] 2019-09-05 12:51
Who should close this issue?

**Comment by martingpritchard** [comment] 2019-09-09 01:18
Hi Alex,
I'll put it on my list to do this week. It's been so long, have forgotten
if I tested the fix....

Cheers,

Martin Pritchard

Pacific Research & Evaluation Associates
m: 0403 440 996 (+61 403 440 996)
e: martin@prea.com.au
w: www.prea.com.au
Skype: pritchardmartin

**Closed** 2019-10-23 01:52 UTC
Labels: In Test, Released
