### ISSUE TITLE
BUG - Subject / Content are not saved when create an Email Task

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#336] opened 2018-07-27 20:08 UTC
### Actual Behaviour:
![image](https://user-images.githubusercontent.com/29519901/43344088-2f823b52-91ae-11e8-8914-e421c779edd8.png)
![image](https://user-images.githubusercontent.com/29519901/43344155-61321f64-91ae-11e8-9941-6cf6e9e205a4.png)

After that I have checked by Edit Task Group and fields are empty

![image](https://user-images.githubusercontent.com/29519901/43344193-851d3c2e-91ae-11e8-8ca2-488077edf24f.png)

### Steps to reproduce the problem

Add Task Group adding below data

**Comment by atl2017** [comment] 2018-07-29 17:31
Tested Ok. Thanks

**Comment by atl2017** [comment] 2018-07-30 17:01
Again happens

**Comment by nap2000** [comment] 2018-07-30 17:51
I'm closing this. I undertook the following steps and the email subject and content are retained.
1. Add Task Group
2. Set a name
3. Select create results from existing
4. Specify email as the assignment type
5. Specify an email address
6. Specify an email option and content
7. select save
8. Select edit task group
The email subject and content are displayed

I have no doubt you are seeing a problem.  Doubtless there is some combination of circumstances that cause an error in the update service.  However rather than re-opening a closed issue with I would ask you to specify the steps that allow the problem to be reproduced.  These steps are key and can be supplemented by screen shots, example forms or even videos if that helps.

**Closed** 2018-07-30 17:51 UTC

**Comment by atl2017** [comment] 2018-07-30 18:25
My steps, that were recording [here:](https://www.useloom.com/share/a4e998bb3fc74e8a93b4d9c866766e93)
are the same as you, except dont have any result

1. Add Task Group
2. Set a name: AUTORIZACION
3. Select create results from existing
4. Specify email as the assignment type
5. Specify an email address
6. Specify an email option and content
7. select save
8. Select edit task group
9. The email subject and content are NOT displayed

**Comment by nap2000** [comment] 2018-07-30 18:47
ok so it must be something in the data.  what is the name of the survey?
were any tasks created?

**Comment by atl2017** [comment] 2018-07-31 01:17
Organisation: SERACIS
Project: Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS
          2 - APROBACION SOLICITUD DE INVENTARIO

Task Group: AUTORIZACION -> Email task

**Comment by nap2000** [comment] 2018-07-31 10:34
OK I followed your steps and a single task was created from the existing data.  When I opened the task in the editor I could see the subject and content.

What are you typing into the subject and content fields.  Do you see a single task being created?

**Comment by atl2017** [comment] 2018-07-31 10:44
Neil, this behaviour is very strange. Now, I have repeated the same process and works.

I will just continue monitoring situation to find out what exactly is triggering the situation.

Thanks

**Comment by nap2000** [comment] 2018-07-31 10:49
There have been no changes to the server.  What I suspect is that the problem might occur when there is no existing data to populate tasks from.  Also that because no results have been submitted for either of the forms then the results tables for one of the other forms do not exist.   I have this as something to investigate but haven't identified the exact steps to reproduce.

This issue should remain closed and if you find a situation that causes task data not to be saved a new issue with the steps to reproduce should be opened.
